// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddNewQuizCard: typeof import('./src/components/MainPage/CreateQuiz/AddNewQuizCard.vue')['default']
    AddQuestionsCard: typeof import('./src/components/MainPage/CreateQuiz/AddQuestionsCard.vue')['default']
    AuthTemplate: typeof import('./src/components/auth/authTemplate.vue')['default']
    Burger: typeof import('./src/components/UI/burger.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    FindAndChoose: typeof import('./src/components/MainPage/SendQuiz/FindUsers/FindAndChoose.vue')['default']
    FindAndChooseMobile: typeof import('./src/components/MainPage/SendQuiz/FindUsers/FindAndChooseMobile.vue')['default']
    LocaleSelect: typeof import('./src/components/UI/LocaleSelect.vue')['default']
    LogOutButton: typeof import('./src/components/UI/LogOutButton.vue')['default']
    Mail: typeof import('./src/components/MainPage/Mail/Mail.vue')['default']
    MainCard: typeof import('./src/components/MainPage/CreateQuiz/MainCard.vue')['default']
    MainMenu: typeof import('./src/components/MainPage/MainMenu/MainMenu.vue')['default']
    MainMenuButtons: typeof import('./src/components/UI/mainMenuButtons.vue')['default']
    MultiplayCorrectAnswers: typeof import('./src/components/MainPage/QuizPlay/MultiplayCorrectAnswers.vue')['default']
    MyQuizzesList: typeof import('./src/components/MainPage/MyQuizzesList/MyQuizzesList.vue')['default']
    OneCorrectAnswer: typeof import('./src/components/MainPage/QuizPlay/OneCorrectAnswer.vue')['default']
    QuestionDialog: typeof import('./src/components/Dialogs/QuestionDialog.vue')['default']
    QuizesList: typeof import('./src/components/MainPage/QuizesList/QuizesList.vue')['default']
    QuizesListAll: typeof import('./src/components/MainPage/QuizesList/QuizesListAll.vue')['default']
    QuizesListIncome: typeof import('./src/components/MainPage/QuizesList/QuizesListIncome.vue')['default']
    QuizesListMail: typeof import('./src/components/MainPage/QuizesList/QuizesListMail.vue')['default']
    QuizPlay: typeof import('./src/components/MainPage/QuizPlay/QuizPlay.vue')['default']
    QuizResultBoard: typeof import('./src/components/MainPage/QuizPlay/QuizResultBoard.vue')['default']
    RefreshButton: typeof import('./src/components/UI/RefreshButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendQuiz: typeof import('./src/components/MainPage/SendQuiz/SendQuiz.vue')['default']
    ToggleThemeButton: typeof import('./src/components/UI/ToggleThemeButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
