// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthTemplate: typeof import('./src/components/auth/authTemplate.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButtom: typeof import('element-plus/es')['ElButtom']
    ElButton: typeof import('element-plus/es')['ElButton']
    'ElButton@': typeof import('element-plus/es')['ElButton@']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ErrorField: typeof import('./src/components/UI/ErrorField.vue')['default']
    Header: typeof import('./src/components/MainPage/Header/Header.vue')['default']
    LocaleSelect: typeof import('./src/components/UI/LocaleSelect.vue')['default']
    LogOutButton: typeof import('./src/components/UI/LogOutButton.vue')['default']
    MainMenu: typeof import('./src/components/MainPage/MainMenu/MainMenu.vue')['default']
    MainMenuButtons: typeof import('./src/components/UI/mainMenuButtons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleThemeButton: typeof import('./src/components/UI/ToggleThemeButton.vue')['default']
    ToogleThemeButton: typeof import('./src/components/UI/ToogleThemeButton.vue')['default']
  }
}
