// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddNewQuizCard: typeof import('./src/components/MainPage/CreateQuiz/AddNewQuizCard.vue')['default']
    AddQuestionsCard: typeof import('./src/components/MainPage/CreateQuiz/AddQuestionsCard.vue')['default']
    AuthTemplate: typeof import('./src/components/auth/authTemplate.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButtom: typeof import('element-plus/es')['ElButtom']
    ElButton: typeof import('element-plus/es')['ElButton']
    'ElButton@': typeof import('element-plus/es')['ElButton@']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ErrorField: typeof import('./src/components/UI/ErrorField.vue')['default']
    Header: typeof import('./src/components/MainPage/Header/Header.vue')['default']
    LocaleSelect: typeof import('./src/components/UI/LocaleSelect.vue')['default']
    LogOutButton: typeof import('./src/components/UI/LogOutButton.vue')['default']
    MainCard: typeof import('./src/components/MainPage/CreateQuiz/MainCard.vue')['default']
    MainMenu: typeof import('./src/components/MainPage/MainMenu/MainMenu.vue')['default']
    MainMenuButtons: typeof import('./src/components/UI/mainMenuButtons.vue')['default']
    MyQuizzesList: typeof import('./src/components/MainPage/MyQuizzesList/MyQuizzesList.vue')['default']
    QuestionDialog: typeof import('./src/components/Dialogs/QuestionDialog.vue')['default']
    QuizPlay: typeof import('./src/components/MainPage/QuizPlay/QuizPlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleThemeButton: typeof import('./src/components/UI/ToggleThemeButton.vue')['default']
    ToogleThemeButton: typeof import('./src/components/UI/ToogleThemeButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
